# FD004 DS-A rerun: held-out Regime 0, five seeds, converged training

**Why this notebook exists.** The archived DS-A notebooks (`03_…Heldout_Regime`, `123/03_…FiveSeed`) never saved a model, and
their fixed 25-epoch training stalls for some seeds: the training loss sits at about 28.9, which is exactly the loss of a
model that predicts constant quantiles (28.88 on the DS-A training targets). Seeds 42 and 789 never escaped that plateau, and
456 and 1000 escaped only in the last epochs. The frozen DS-A result (RMSE 24.869) can't be rebuilt from anything archived.

**What stays the same as the frozen pipeline:** data, k-means regimes (seed 42), engine split (174/37/38, seed 42),
Regime 0 endpoint exclusion, training-only sensor scaling, 30-cycle consecutive windows, 14 sensors + 6 one-hot regimes,
20→18 projection, BiLSTM(64) with temporal attention, q10/q50/q90 pinball loss, Adam 1e-3, batch 256, Asymmetric CQR
(α/2 per tail, finite-sample `higher`) and Balanced Engine CQR (within-engine default 0.80 quantile, then the across-engine
finite-sample `higher` quantile), intervals clipped at 0.

**What changes (pre-specified in Part A, before any test result exists):** how long each model trains.
- 20% of the 174 training engines (35 engines, fixed split seed 42) become an **internal validation** set.
  These are training engines, not calibration or test engines. The model is fitted on the other 139.
- Train up to 150 epochs. Early stopping watches internal-validation pinball loss, patience 15, not before epoch 30,
  and restores the best weights.
- **Convergence check (training data only):** a run counts as converged if its best internal-validation loss is at most
  0.60 × the constant-quantile loss on the same validation windows. Every seed is reported either way. No seed is
  replaced or dropped, so nothing is selected on test outcomes.

**Order of operations.** Part A writes the protocol. Part B trains all five seeds, saves every model, and runs the
convergence check, without touching test windows. Part C evaluates the test windows only after Part B's results are
on disk. Don't change Part A after Part C has run.

Run on Colab with a GPU (Runtime → Change runtime type), or locally. For a quick pipeline check, set the environment variable `FD004_SMOKE=1` (1 seed, 3 epochs, separate output folder).

In [1]:
# ---------- Paths and run mode ----------
import os, sys, json, time, random, hashlib, platform
from pathlib import Path

SMOKE_TEST = os.environ.get("FD004_SMOKE") == "1"   # True = 1 seed, 3 epochs, output to *_SMOKE folder (pipeline check only, results meaningless)

def _find_root():
    candidates = [os.environ.get("FD004_ROOT", ""),
                  "/content/drive/MyDrive/FD004_Research",
                  str(Path.home() / "Downloads/FD004_Research")]
    for c in candidates:
        if c and Path(c, "CMAPSSData/train_FD004.txt").exists():
            return Path(c)
    raise FileNotFoundError("Set FD004_ROOT to the FD004_Research folder (it must contain CMAPSSData/train_FD004.txt).")

if "google.colab" in sys.modules and not Path("/content/drive/MyDrive").exists():
    from google.colab import drive
    drive.mount("/content/drive")

ROOT = _find_root()
DATA_PATH = ROOT / "CMAPSSData/train_FD004.txt"
OUT = Path(os.environ.get("FD004_OUT") or ROOT / ("FD004_DS_A_Rerun_Results_SMOKE" if SMOKE_TEST else "FD004_DS_A_Rerun_Results"))
(OUT / "models").mkdir(parents=True, exist_ok=True)
(OUT / "histories").mkdir(exist_ok=True)
print("Root:", ROOT)
print("Output:", OUT)

Root: <FD004_ROOT>
Output: <FD004_ROOT>/FD004_DS_A_Rerun_Results

## Part A: protocol (written before any training or test evaluation)

In [2]:
PROTOCOL = {
    "experiment": "FD004 DS-A held-out Regime 0, converged five-seed rerun",
    "created_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
    "data_seed": 42,                      # k-means, engine split, internal-validation split
    "model_seeds": [42] if SMOKE_TEST else [42, 123, 456, 789, 1000],
    "held_out_regime": 0,
    "n_regimes": 6,
    "rul_clip": 125,
    "window_size": 30,
    "settings": ["setting_1", "setting_2", "setting_3"],
    "sensors": ["s_2", "s_3", "s_4", "s_7", "s_8", "s_9", "s_11", "s_12", "s_13", "s_14", "s_15", "s_17", "s_20", "s_21"],
    "split": {"test_size_first": 0.30, "test_size_second": 0.50, "expected_counts": [174, 37, 38]},
    "internal_validation": {"fraction_of_train_engines": 0.20, "split_seed": 42,
                            "note": "training engines only; endpoints filtered exactly like training"},
    "model": {"projection": 18, "bilstm_units": 64, "attention": "FastTemporalAttention",
              "quantiles": [0.10, 0.50, 0.90], "optimizer": "Adam", "learning_rate": 1e-3, "batch_size": 256},
    "training_rule": {"max_epochs": 3 if SMOKE_TEST else 150, "monitor": "val_loss", "patience": 15,
                      "start_from_epoch": 0 if SMOKE_TEST else 30, "restore_best_weights": True},
    "convergence_check": {"rule": "best_val_loss <= ratio * constant_quantile_val_loss", "ratio": 0.60,
                          "constant_quantiles_fitted_on": "fit engines (training engines minus internal validation)",
                          "failed_seeds": "reported and flagged; never replaced or dropped"},
    "calibration": {"alpha": 0.20,
                    "asymmetric": "finite-sample higher quantile at ceil((n+1)(1-alpha/2))/n per tail",
                    "balanced": "within-engine np.quantile(.,0.80) default, then ceil((M+1)(1-alpha))/M higher across engines",
                    "interval_clip_at_zero": True},
    "life_stage": {"Early": "RUL > 80", "Mid": "40 < RUL <= 80", "Late": "RUL <= 40"},
    "bootstrap": {"replicates": 10000, "unit": "test engine", "rng_seed": 42, "ci": [2.5, 97.5]},
    "primary_report": "all five seeds (mean and SD); seed 42 as the single-run reference",
    "secondary_report": "converged seeds only, labelled as such",
}
protocol_path = OUT / "protocol.json"
if protocol_path.exists() and not SMOKE_TEST:
    old = json.loads(protocol_path.read_text())
    changed = {k for k in PROTOCOL if k != "created_utc" and old.get(k) != PROTOCOL[k]}
    assert not changed, f"Protocol already registered and differs in {changed}. Don't edit Part A after a run."
    PROTOCOL["created_utc"] = old["created_utc"]
else:
    protocol_path.write_text(json.dumps(PROTOCOL, indent=2))
print("Protocol sha256:", hashlib.sha256(protocol_path.read_bytes()).hexdigest()[:16])

Protocol sha256: b63e5994f690bcc6

## Data, regimes, split and windows (identical to the frozen DS-A pipeline)

In [3]:
import numpy as np
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

P = PROTOCOL
SET, SENS, W, HO = P["settings"], P["sensors"], P["window_size"], P["held_out_regime"]
cols = ["unit_id", "time_cycles"] + SET + [f"s_{i}" for i in range(1, 22)]

raw = pd.read_csv(DATA_PATH, sep=r"\s+", header=None).iloc[:, :len(cols)]
raw.columns = cols
raw["RUL"] = (raw.groupby("unit_id")["time_cycles"].transform("max") - raw["time_cycles"]).clip(upper=P["rul_clip"])

setting_scaler = StandardScaler().fit(raw[SET])
kmeans = KMeans(n_clusters=P["n_regimes"], random_state=P["data_seed"], n_init=10)
raw["regime"] = kmeans.fit_predict(setting_scaler.transform(raw[SET]))
assert len(raw) == 61249
print("Regime counts:", raw["regime"].value_counts().sort_index().to_dict())
assert raw["regime"].value_counts()[HO] == 15395, "Regime 0 size differs from the frozen run"

engines = np.array(sorted(raw["unit_id"].unique()))
train_engines, temp = train_test_split(engines, test_size=0.30, random_state=P["data_seed"])
cal_engines, test_engines = train_test_split(temp, test_size=0.50, random_state=P["data_seed"])
assert [len(train_engines), len(cal_engines), len(test_engines)] == P["split"]["expected_counts"]

# Same split code as DS-B; check it against the frozen DS-B split file when available.
dsb_split = ROOT / "FD004_DS_B_Results/DS_B_Engine_Split.csv"
if dsb_split.exists():
    s = pd.read_csv(dsb_split)
    assert set(s.loc[s.split == "test", "unit_id"]) == set(test_engines), "Test engines differ from the frozen split"
    assert set(s.loc[s.split == "calibration", "unit_id"]) == set(cal_engines)
    print("Engine split matches the frozen split file.")

fit_engines, ival_engines = train_test_split(train_engines, test_size=P["internal_validation"]["fraction_of_train_engines"],
                                             random_state=P["internal_validation"]["split_seed"])
print(f"Train engines {len(train_engines)} -> fit {len(fit_engines)} + internal validation {len(ival_engines)}")

# Sensor scaler: all 174 training engines, non-held-out rows (as in the frozen DS-A notebook).
sensor_scaler = StandardScaler().fit(raw.loc[raw.unit_id.isin(train_engines) & (raw.regime != HO), SENS])
traj = raw.copy()
traj[SENS] = sensor_scaler.transform(traj[SENS])
traj = traj.sort_values(["unit_id", "time_cycles"]).reset_index(drop=True)

def make_windows(engine_ids, mode):
    X, y, ids, cyc = [], [], [], []
    eye = np.eye(P["n_regimes"], dtype=np.float32)
    for e in sorted(engine_ids):
        g = traj[traj.unit_id == e]
        sens = g[SENS].to_numpy(np.float32); reg = g["regime"].to_numpy()
        rul = g["RUL"].to_numpy(np.float32); t = g["time_cycles"].to_numpy()
        for end in range(W - 1, len(g)):
            if (reg[end] == HO) != (mode == "heldout"):
                continue
            sl = slice(end - W + 1, end + 1)
            assert np.all(np.diff(t[sl]) == 1)
            X.append(np.concatenate([sens[sl], eye[reg[sl]]], axis=-1))
            y.append(rul[end]); ids.append(e); cyc.append(t[end])
    return np.asarray(X), np.asarray(y, np.float32), np.asarray(ids), np.asarray(cyc)

X_fit, y_fit, id_fit, _ = make_windows(fit_engines, "seen")
X_iv, y_iv, id_iv, _ = make_windows(ival_engines, "seen")
X_cal, y_cal, id_cal, cyc_cal = make_windows(cal_engines, "seen")
X_test, y_test, id_test, cyc_test = make_windows(test_engines, "heldout")   # not used until Part C

assert len(y_fit) + len(y_iv) == 28322 and len(y_cal) == 6021 and len(y_test) == 2043, "Window counts differ from frozen"
print("fit", X_fit.shape, "| internal val", X_iv.shape, "| cal", X_cal.shape, "| test", X_test.shape)

np.savez(OUT / "preprocessing.npz",
         kmeans_centers=kmeans.cluster_centers_, setting_mean=setting_scaler.mean_, setting_scale=setting_scaler.scale_,
         sensor_mean=sensor_scaler.mean_, sensor_scale=sensor_scaler.scale_)
pd.concat([pd.DataFrame({"split": n, "unit_id": v}) for n, v in
           [("fit", fit_engines), ("internal_val", ival_engines), ("calibration", cal_engines), ("test", test_engines)]]
          ).to_csv(OUT / "engine_split.csv", index=False)

Regime counts: {0: 15395, 1: 9224, 2: 9139, 3: 9091, 4: 9238, 5: 9162}
Engine split matches the frozen split file.
Train engines 174 -> fit 139 + internal validation 35

fit (22569, 30, 20) | internal val (5753, 30, 20) | cal (6021, 30, 20) | test (2043, 30, 20)

## Part B: train five seeds and check convergence (no test data)

In [4]:
import tensorflow as tf
from tensorflow.keras.layers import Input, Dense, LSTM, Bidirectional, Layer
from tensorflow.keras.models import Model

Q = P["model"]["quantiles"]

@tf.keras.utils.register_keras_serializable(package="fd004")
class FastTemporalAttention(Layer):
    def build(self, input_shape):
        d = input_shape[-1]
        self.W = self.add_weight(name="W", shape=(d, d), initializer="glorot_uniform")
        self.b = self.add_weight(name="b", shape=(d,), initializer="zeros")
        self.v = self.add_weight(name="v", shape=(d, 1), initializer="glorot_uniform")
        super().build(input_shape)
    def call(self, x):
        e = tf.nn.tanh(tf.tensordot(x, self.W, axes=1) + self.b)
        w = tf.nn.softmax(tf.tensordot(e, self.v, axes=1), axis=1)
        return tf.reduce_sum(x * w, axis=1)

@tf.keras.utils.register_keras_serializable(package="fd004")
def multi_quantile_pinball_loss(y_true, y_pred):
    y_true = tf.cast(tf.reshape(y_true, (-1, 1)), tf.float32)
    losses = [tf.maximum(q * (y_true - y_pred[:, i:i+1]), (q - 1.0) * (y_true - y_pred[:, i:i+1])) for i, q in enumerate(Q)]
    return tf.reduce_mean(tf.add_n(losses))

def build_model():
    m = P["model"]
    inp = Input(shape=(W, 20), name="input_window")
    h = Dense(m["projection"], use_bias=False, name="projection")(inp)
    h = Bidirectional(LSTM(m["bilstm_units"], return_sequences=True), name="bilstm")(h)
    h = FastTemporalAttention(name="temporal_attention")(h)
    out = Dense(3, activation="linear", name="quantiles")(h)
    model = Model(inp, out, name="FD004_DS_A_rerun")
    model.compile(optimizer=tf.keras.optimizers.Adam(m["learning_rate"]), loss=multi_quantile_pinball_loss)
    return model

def set_seed(s):
    random.seed(s); np.random.seed(s); tf.random.set_seed(s); os.environ["PYTHONHASHSEED"] = str(s)

def constant_quantile_loss(y_ref, y_eval):
    return float(sum(np.mean(np.maximum(q * (y_eval - np.quantile(y_ref, q)), (q - 1) * (y_eval - np.quantile(y_ref, q))))
                     for q in Q))

const_iv = constant_quantile_loss(y_fit, y_iv)
print(f"Constant-quantile loss on internal validation: {const_iv:.3f}  -> convergence threshold "
      f"{P['convergence_check']['ratio'] * const_iv:.3f}")

env = {"python": platform.python_version(), "platform": platform.platform(), "tensorflow": tf.__version__,
       "numpy": np.__version__, "pandas": pd.__version__,
       "gpu": [d.name for d in tf.config.list_physical_devices("GPU")]}
(OUT / "environment.json").write_text(json.dumps(env, indent=2))
print(env)

Constant-quantile loss on internal validation: 29.081  -> convergence threshold 17.449
{'python': '3.12.13', 'platform': 'macOS-26.5.2-arm64-arm-64bit', 'tensorflow': '2.20.0', 'numpy': '2.0.2', 'pandas': '2.2.3', 'gpu': []}

In [5]:
tr = P["training_rule"]
train_log = []
for seed in P["model_seeds"]:
    tf.keras.backend.clear_session()
    set_seed(seed)
    model = build_model()
    stop = tf.keras.callbacks.EarlyStopping(monitor=tr["monitor"], patience=tr["patience"],
                                            start_from_epoch=tr["start_from_epoch"], restore_best_weights=tr["restore_best_weights"])
    t0 = time.time()
    hist = model.fit(X_fit, y_fit, validation_data=(X_iv, y_iv), epochs=tr["max_epochs"],
                     batch_size=P["model"]["batch_size"], shuffle=True, callbacks=[stop], verbose=2)
    h = pd.DataFrame(hist.history); h.insert(0, "epoch", np.arange(1, len(h) + 1))
    h.to_csv(OUT / "histories" / f"seed{seed}_history.csv", index=False)
    model.save(OUT / "models" / f"DS_A_rerun_seed{seed}.keras")
    best = float(h["val_loss"].min())
    train_log.append({"seed": seed, "epochs_run": len(h), "best_epoch": int(h.loc[h.val_loss.idxmin(), "epoch"]),
                      "best_val_loss": best, "final_train_loss": float(h["loss"].iloc[-1]),
                      "constant_val_loss": const_iv, "ratio": best / const_iv,
                      "converged": best <= P["convergence_check"]["ratio"] * const_iv,
                      "minutes": (time.time() - t0) / 60})
    print(train_log[-1])

train_log = pd.DataFrame(train_log)
train_log.to_csv(OUT / "convergence_check.csv", index=False)
display(train_log.round(3))
if not train_log.converged.all():
    print("WARNING: some seeds did not converge. They stay in the primary report, flagged. Don't rerun with new seeds.")

Epoch 1/150

89/89 - 5s - 60ms/step - loss: 118.2158 - val_loss: 103.8230

Epoch 2/150

89/89 - 4s - 50ms/step - loss: 96.7650 - val_loss: 88.9148

Epoch 3/150

89/89 - 5s - 52ms/step - loss: 83.5254 - val_loss: 77.1892

Epoch 4/150

89/89 - 5s - 52ms/step - loss: 72.6869 - val_loss: 67.3884

Epoch 5/150

89/89 - 5s - 54ms/step - loss: 63.5406 - val_loss: 59.0897

Epoch 6/150

89/89 - 5s - 52ms/step - loss: 55.7956 - val_loss: 52.0896

Epoch 7/150

89/89 - 5s - 59ms/step - loss: 49.2201 - val_loss: 46.1551

Epoch 8/150

89/89 - 10s - 110ms/step - loss: 43.6613 - val_loss: 41.1680

Epoch 9/150

89/89 - 11s - 123ms/step - loss: 39.0062 - val_loss: 36.9869

Epoch 10/150

89/89 - 8s - 92ms/step - loss: 35.1093 - val_loss: 33.4937

Epoch 11/150

89/89 - 8s - 92ms/step - loss: 31.8403 - val_loss: 30.5677

Epoch 12/150

89/89 - 9s - 102ms/step - loss: 29.4631 - val_loss: 29.3363

Epoch 13/150

89/89 - 9s - 97ms/step - loss: 29.0540 - val_loss: 29.2216

Epoch 14/150

89/89 - 7s - 83ms/step - loss: 28.9584 - val_loss: 29.1548

Epoch 15/150

89/89 - 7s - 81ms/step - loss: 28.9030 - val_loss: 29.1183

Epoch 16/150

89/89 - 7s - 81ms/step - loss: 28.8713 - val_loss: 29.0987

Epoch 17/150

89/89 - 7s - 82ms/step - loss: 28.8537 - val_loss: 29.0891

Epoch 18/150

89/89 - 7s - 82ms/step - loss: 28.8449 - val_loss: 29.0852

Epoch 19/150

89/89 - 7s - 81ms/step - loss: 28.8233 - val_loss: 29.0833

Epoch 20/150

89/89 - 11s - 129ms/step - loss: 28.8345 - val_loss: 29.0842

Epoch 21/150

89/89 - 10s - 107ms/step - loss: 28.8332 - val_loss: 29.0839

Epoch 22/150

89/89 - 8s - 89ms/step - loss: 28.8383 - val_loss: 29.0851

Epoch 23/150

89/89 - 8s - 87ms/step - loss: 28.8355 - val_loss: 29.0845

Epoch 24/150

89/89 - 8s - 85ms/step - loss: 28.8314 - val_loss: 29.0812

Epoch 25/150

89/89 - 8s - 86ms/step - loss: 28.8306 - val_loss: 29.0849

Epoch 26/150

89/89 - 8s - 85ms/step - loss: 28.8357 - val_loss: 29.0848

Epoch 27/150

89/89 - 8s - 88ms/step - loss: 28.8355 - val_loss: 29.0845

Epoch 28/150

89/89 - 8s - 86ms/step - loss: 28.8354 - val_loss: 29.0844

Epoch 29/150

89/89 - 8s - 87ms/step - loss: 28.8354 - val_loss: 29.0842

Epoch 30/150

89/89 - 8s - 88ms/step - loss: 28.8354 - val_loss: 29.0842

Epoch 31/150

89/89 - 7s - 84ms/step - loss: 28.8354 - val_loss: 29.0843

Epoch 32/150

89/89 - 8s - 87ms/step - loss: 28.8354 - val_loss: 29.0842

Epoch 33/150

89/89 - 8s - 90ms/step - loss: 28.8354 - val_loss: 29.0842

Epoch 34/150

89/89 - 8s - 88ms/step - loss: 28.8354 - val_loss: 29.0841

Epoch 35/150

89/89 - 9s - 96ms/step - loss: 28.8353 - val_loss: 29.0840

Epoch 36/150

89/89 - 8s - 87ms/step - loss: 28.8354 - val_loss: 29.0838

Epoch 37/150

89/89 - 8s - 89ms/step - loss: 28.8352 - val_loss: 29.0837

Epoch 38/150

89/89 - 8s - 86ms/step - loss: 28.8351 - val_loss: 29.0834

Epoch 39/150

89/89 - 8s - 86ms/step - loss: 28.8351 - val_loss: 29.0835

Epoch 40/150

89/89 - 8s - 92ms/step - loss: 28.8349 - val_loss: 29.0834

Epoch 41/150

89/89 - 8s - 86ms/step - loss: 28.8347 - val_loss: 29.0830

Epoch 42/150

89/89 - 8s - 88ms/step - loss: 28.8342 - val_loss: 29.0816

Epoch 43/150

89/89 - 8s - 95ms/step - loss: 28.8334 - val_loss: 29.0796

Epoch 44/150

89/89 - 8s - 86ms/step - loss: 28.8316 - val_loss: 29.0765

Epoch 45/150

89/89 - 8s - 90ms/step - loss: 28.8272 - val_loss: 29.0670

Epoch 46/150

89/89 - 8s - 88ms/step - loss: 28.8045 - val_loss: 28.9961

Epoch 47/150

89/89 - 8s - 91ms/step - loss: 28.5729 - val_loss: 29.0737

Epoch 48/150

89/89 - 8s - 87ms/step - loss: 28.7503 - val_loss: 28.9540

Epoch 49/150

89/89 - 8s - 85ms/step - loss: 28.5665 - val_loss: 28.8138

Epoch 50/150

89/89 - 8s - 94ms/step - loss: 28.2858 - val_loss: 28.3784

Epoch 51/150

89/89 - 8s - 90ms/step - loss: 26.8024 - val_loss: 27.3664

Epoch 52/150

89/89 - 8s - 86ms/step - loss: 21.5977 - val_loss: 19.7758

Epoch 53/150

89/89 - 8s - 86ms/step - loss: 18.0124 - val_loss: 17.7008

Epoch 54/150

89/89 - 8s - 87ms/step - loss: 16.5391 - val_loss: 15.9745

Epoch 55/150

89/89 - 8s - 88ms/step - loss: 15.5953 - val_loss: 15.2871

Epoch 56/150

89/89 - 8s - 86ms/step - loss: 15.1759 - val_loss: 15.0235

Epoch 57/150

89/89 - 8s - 88ms/step - loss: 14.7001 - val_loss: 14.1985

Epoch 58/150

89/89 - 8s - 87ms/step - loss: 14.2563 - val_loss: 13.0826

Epoch 59/150

89/89 - 8s - 94ms/step - loss: 13.8734 - val_loss: 13.1737

Epoch 60/150

89/89 - 8s - 92ms/step - loss: 13.5527 - val_loss: 12.7260

Epoch 61/150

89/89 - 7s - 83ms/step - loss: 13.3556 - val_loss: 12.7601

Epoch 62/150

89/89 - 7s - 82ms/step - loss: 12.9183 - val_loss: 12.2080

Epoch 63/150

89/89 - 7s - 83ms/step - loss: 12.6996 - val_loss: 11.8921

Epoch 64/150

89/89 - 8s - 84ms/step - loss: 12.5286 - val_loss: 11.9447

Epoch 65/150

89/89 - 7s - 83ms/step - loss: 12.3354 - val_loss: 11.8822

Epoch 66/150

89/89 - 8s - 85ms/step - loss: 12.1870 - val_loss: 12.5929

Epoch 67/150

89/89 - 7s - 79ms/step - loss: 12.1188 - val_loss: 11.4282

Epoch 68/150

89/89 - 7s - 81ms/step - loss: 11.8796 - val_loss: 11.3593

Epoch 69/150

89/89 - 7s - 81ms/step - loss: 11.8309 - val_loss: 12.0078

Epoch 70/150

89/89 - 7s - 83ms/step - loss: 11.8726 - val_loss: 11.3823

Epoch 71/150

89/89 - 7s - 84ms/step - loss: 11.5167 - val_loss: 11.0788

Epoch 72/150

89/89 - 7s - 84ms/step - loss: 11.4064 - val_loss: 11.1693

Epoch 73/150

89/89 - 7s - 83ms/step - loss: 11.2924 - val_loss: 11.0858

Epoch 74/150

89/89 - 8s - 85ms/step - loss: 11.3087 - val_loss: 11.4785

Epoch 75/150

89/89 - 8s - 85ms/step - loss: 11.1369 - val_loss: 11.2218

Epoch 76/150

89/89 - 7s - 82ms/step - loss: 11.1001 - val_loss: 11.1274

Epoch 77/150

89/89 - 7s - 84ms/step - loss: 10.9470 - val_loss: 11.2411

Epoch 78/150

89/89 - 7s - 84ms/step - loss: 10.9506 - val_loss: 11.3715

Epoch 79/150

89/89 - 7s - 83ms/step - loss: 11.0332 - val_loss: 11.2127

Epoch 80/150

89/89 - 7s - 81ms/step - loss: 10.8132 - val_loss: 11.8981

Epoch 81/150

89/89 - 7s - 80ms/step - loss: 10.5313 - val_loss: 11.3273

Epoch 82/150

89/89 - 7s - 84ms/step - loss: 10.5824 - val_loss: 11.5013

Epoch 83/150

89/89 - 7s - 83ms/step - loss: 10.4947 - val_loss: 11.5746

Epoch 84/150

89/89 - 7s - 83ms/step - loss: 10.2031 - val_loss: 11.1160

Epoch 85/150

89/89 - 8s - 85ms/step - loss: 10.2795 - val_loss: 11.4277

Epoch 86/150

89/89 - 7s - 81ms/step - loss: 10.1070 - val_loss: 11.3580

{'seed': 42, 'epochs_run': 86, 'best_epoch': 71, 'best_val_loss': 11.078849792480469, 'final_train_loss': 10.106950759887695, 'constant_val_loss': 29.081470489501953, 'ratio': 0.38095906451772427, 'converged': True, 'minutes': 10.852291429042817}

Epoch 1/150

89/89 - 8s - 93ms/step - loss: 117.4418 - val_loss: 103.2677

Epoch 2/150

89/89 - 7s - 77ms/step - loss: 96.3201 - val_loss: 88.5244

Epoch 3/150

89/89 - 7s - 84ms/step - loss: 83.2017 - val_loss: 76.8847

Epoch 4/150

89/89 - 7s - 81ms/step - loss: 72.4221 - val_loss: 67.1300

Epoch 5/150

89/89 - 8s - 86ms/step - loss: 63.2832 - val_loss: 58.8248

Epoch 6/150

89/89 - 7s - 78ms/step - loss: 55.5061 - val_loss: 51.8563

Epoch 7/150

89/89 - 7s - 81ms/step - loss: 48.9476 - val_loss: 45.8085

Epoch 8/150

89/89 - 7s - 79ms/step - loss: 43.3276 - val_loss: 40.8387

Epoch 9/150

89/89 - 7s - 82ms/step - loss: 38.6752 - val_loss: 36.6732

Epoch 10/150

89/89 - 7s - 81ms/step - loss: 34.7967 - val_loss: 33.2086

Epoch 11/150

89/89 - 7s - 79ms/step - loss: 31.5840 - val_loss: 30.3217

Epoch 12/150

89/89 - 7s - 81ms/step - loss: 29.3820 - val_loss: 29.3570

Epoch 13/150

89/89 - 8s - 89ms/step - loss: 29.0695 - val_loss: 29.2378

Epoch 14/150

89/89 - 7s - 80ms/step - loss: 28.9643 - val_loss: 29.1659

Epoch 15/150

89/89 - 7s - 80ms/step - loss: 28.9054 - val_loss: 29.1233

Epoch 16/150

89/89 - 7s - 80ms/step - loss: 28.8618 - val_loss: 29.1110

Epoch 17/150

89/89 - 7s - 80ms/step - loss: 28.8417 - val_loss: 29.0906

Epoch 18/150

89/89 - 7s - 79ms/step - loss: 28.8465 - val_loss: 29.0260

Epoch 19/150

89/89 - 7s - 77ms/step - loss: 28.8166 - val_loss: 29.0823

Epoch 20/150

89/89 - 7s - 79ms/step - loss: 28.3937 - val_loss: 28.5510

Epoch 21/150

89/89 - 7s - 82ms/step - loss: 28.5959 - val_loss: 27.8571

Epoch 22/150

89/89 - 7s - 84ms/step - loss: 27.3924 - val_loss: 25.6339

Epoch 23/150

89/89 - 7s - 81ms/step - loss: 26.5707 - val_loss: 26.7288

Epoch 24/150

89/89 - 7s - 82ms/step - loss: 28.9553 - val_loss: 28.5165

Epoch 25/150

89/89 - 7s - 80ms/step - loss: 27.2132 - val_loss: 28.1751

Epoch 26/150

89/89 - 7s - 80ms/step - loss: 24.4248 - val_loss: 20.6857

Epoch 27/150

89/89 - 7s - 80ms/step - loss: 22.9531 - val_loss: 21.8986

Epoch 28/150

89/89 - 7s - 82ms/step - loss: 20.8499 - val_loss: 19.3263

Epoch 29/150

89/89 - 7s - 82ms/step - loss: 19.4808 - val_loss: 18.3380

Epoch 30/150

89/89 - 8s - 84ms/step - loss: 19.4346 - val_loss: 26.0321

Epoch 31/150

89/89 - 7s - 82ms/step - loss: 22.4320 - val_loss: 24.9315

Epoch 32/150

89/89 - 7s - 80ms/step - loss: 22.9301 - val_loss: 21.0293

Epoch 33/150

89/89 - 7s - 82ms/step - loss: 19.1357 - val_loss: 17.8270

Epoch 34/150

89/89 - 7s - 81ms/step - loss: 17.7446 - val_loss: 16.5230

Epoch 35/150

89/89 - 7s - 83ms/step - loss: 16.8868 - val_loss: 17.3960

Epoch 36/150

89/89 - 7s - 80ms/step - loss: 16.5460 - val_loss: 15.6614

Epoch 37/150

89/89 - 7s - 82ms/step - loss: 16.4127 - val_loss: 15.9630

Epoch 38/150

89/89 - 7s - 81ms/step - loss: 15.8949 - val_loss: 15.3946

Epoch 39/150

89/89 - 7s - 84ms/step - loss: 15.2928 - val_loss: 13.9651

Epoch 40/150

89/89 - 7s - 83ms/step - loss: 14.8042 - val_loss: 13.5502

Epoch 41/150

89/89 - 7s - 82ms/step - loss: 14.5906 - val_loss: 13.5169

Epoch 42/150

89/89 - 7s - 82ms/step - loss: 14.9542 - val_loss: 14.4985

Epoch 43/150

89/89 - 7s - 84ms/step - loss: 14.6527 - val_loss: 13.1130

Epoch 44/150

89/89 - 7s - 82ms/step - loss: 14.0478 - val_loss: 12.8857

Epoch 45/150

89/89 - 7s - 82ms/step - loss: 13.6438 - val_loss: 12.3069

Epoch 46/150

89/89 - 8s - 88ms/step - loss: 13.5832 - val_loss: 12.4069

Epoch 47/150

89/89 - 7s - 84ms/step - loss: 13.2725 - val_loss: 11.7881

Epoch 48/150

89/89 - 7s - 82ms/step - loss: 12.9855 - val_loss: 11.7074

Epoch 49/150

89/89 - 7s - 82ms/step - loss: 12.7515 - val_loss: 11.9763

Epoch 50/150

89/89 - 7s - 82ms/step - loss: 12.5653 - val_loss: 11.3700

Epoch 51/150

89/89 - 7s - 81ms/step - loss: 12.4130 - val_loss: 11.1173

Epoch 52/150

89/89 - 7s - 82ms/step - loss: 12.3416 - val_loss: 10.9706

Epoch 53/150

89/89 - 7s - 82ms/step - loss: 12.2026 - val_loss: 11.8192

Epoch 54/150

89/89 - 7s - 81ms/step - loss: 12.1953 - val_loss: 10.8743

Epoch 55/150

89/89 - 7s - 81ms/step - loss: 11.9084 - val_loss: 11.1819

Epoch 56/150

89/89 - 7s - 80ms/step - loss: 11.9160 - val_loss: 11.1924

Epoch 57/150

89/89 - 7s - 82ms/step - loss: 11.7056 - val_loss: 10.9165

Epoch 58/150

89/89 - 7s - 82ms/step - loss: 11.7132 - val_loss: 10.9997

Epoch 59/150

89/89 - 7s - 83ms/step - loss: 11.6774 - val_loss: 10.8988

Epoch 60/150

89/89 - 7s - 81ms/step - loss: 11.6147 - val_loss: 10.8408

Epoch 61/150

89/89 - 7s - 81ms/step - loss: 11.5337 - val_loss: 10.6774

Epoch 62/150

89/89 - 7s - 82ms/step - loss: 11.3720 - val_loss: 10.6614

Epoch 63/150

89/89 - 7s - 81ms/step - loss: 11.5847 - val_loss: 10.7806

Epoch 64/150

89/89 - 7s - 84ms/step - loss: 11.4352 - val_loss: 11.0248

Epoch 65/150

89/89 - 7s - 81ms/step - loss: 11.1902 - val_loss: 11.8608

Epoch 66/150

89/89 - 7s - 81ms/step - loss: 11.5241 - val_loss: 10.6868

Epoch 67/150

89/89 - 7s - 82ms/step - loss: 11.1413 - val_loss: 10.6281

Epoch 68/150

89/89 - 7s - 84ms/step - loss: 11.1403 - val_loss: 10.8765

Epoch 69/150

89/89 - 7s - 83ms/step - loss: 11.1148 - val_loss: 10.8105

Epoch 70/150

89/89 - 7s - 81ms/step - loss: 11.1514 - val_loss: 10.6053

Epoch 71/150

89/89 - 7s - 82ms/step - loss: 10.9821 - val_loss: 10.6796

Epoch 72/150

89/89 - 7s - 83ms/step - loss: 11.0980 - val_loss: 10.9095

Epoch 73/150

89/89 - 7s - 80ms/step - loss: 10.8876 - val_loss: 10.8784

Epoch 74/150

89/89 - 7s - 78ms/step - loss: 11.1378 - val_loss: 10.7591

Epoch 75/150

89/89 - 7s - 80ms/step - loss: 10.6976 - val_loss: 10.6038

Epoch 76/150

89/89 - 7s - 79ms/step - loss: 10.5679 - val_loss: 10.6827

Epoch 77/150

89/89 - 7s - 80ms/step - loss: 10.7313 - val_loss: 10.7938

Epoch 78/150

89/89 - 7s - 79ms/step - loss: 10.5217 - val_loss: 10.9724

Epoch 79/150

89/89 - 7s - 79ms/step - loss: 10.3742 - val_loss: 10.6423

Epoch 80/150

89/89 - 7s - 78ms/step - loss: 10.3397 - val_loss: 10.8235

Epoch 81/150

89/89 - 7s - 82ms/step - loss: 10.3353 - val_loss: 10.9289

Epoch 82/150

89/89 - 7s - 81ms/step - loss: 10.4355 - val_loss: 10.9006

Epoch 83/150

89/89 - 7s - 80ms/step - loss: 10.1915 - val_loss: 11.1409

Epoch 84/150

89/89 - 7s - 79ms/step - loss: 10.2138 - val_loss: 10.9828

Epoch 85/150

89/89 - 7s - 78ms/step - loss: 9.9852 - val_loss: 11.0436

Epoch 86/150

89/89 - 7s - 79ms/step - loss: 9.9661 - val_loss: 10.7890

Epoch 87/150

89/89 - 7s - 80ms/step - loss: 9.8578 - val_loss: 10.6821

Epoch 88/150

89/89 - 7s - 78ms/step - loss: 9.9073 - val_loss: 11.2403

Epoch 89/150

89/89 - 7s - 80ms/step - loss: 9.7664 - val_loss: 10.6816

Epoch 90/150

89/89 - 7s - 79ms/step - loss: 9.9646 - val_loss: 10.7191

{'seed': 123, 'epochs_run': 90, 'best_epoch': 75, 'best_val_loss': 10.603796005249023, 'final_train_loss': 9.964648246765137, 'constant_val_loss': 29.081470489501953, 'ratio': 0.3646237905705924, 'converged': True, 'minutes': 10.86125079790751}

Epoch 1/150

89/89 - 8s - 91ms/step - loss: 117.9370 - val_loss: 104.3169

Epoch 2/150

89/89 - 7s - 74ms/step - loss: 97.2540 - val_loss: 89.4053

Epoch 3/150

89/89 - 7s - 77ms/step - loss: 84.0382 - val_loss: 77.6896

Epoch 4/150

89/89 - 7s - 78ms/step - loss: 73.2095 - val_loss: 67.8851

Epoch 5/150

89/89 - 7s - 80ms/step - loss: 64.0658 - val_loss: 59.5770

Epoch 6/150

89/89 - 7s - 78ms/step - loss: 56.3075 - val_loss: 52.5342

Epoch 7/150

89/89 - 7s - 79ms/step - loss: 49.6718 - val_loss: 46.5559

Epoch 8/150

89/89 - 7s - 83ms/step - loss: 44.0700 - val_loss: 41.5334

Epoch 9/150

89/89 - 7s - 79ms/step - loss: 39.3704 - val_loss: 37.2748

Epoch 10/150

89/89 - 8s - 94ms/step - loss: 35.3822 - val_loss: 33.7342

Epoch 11/150

89/89 - 7s - 80ms/step - loss: 32.0756 - val_loss: 30.7694

Epoch 12/150

89/89 - 7s - 80ms/step - loss: 29.5710 - val_loss: 29.3469

Epoch 13/150

89/89 - 7s - 75ms/step - loss: 29.0660 - val_loss: 29.2307

Epoch 14/150

89/89 - 7s - 75ms/step - loss: 28.9681 - val_loss: 29.1637

Epoch 15/150

89/89 - 7s - 74ms/step - loss: 28.9107 - val_loss: 29.1302

Epoch 16/150

89/89 - 7s - 74ms/step - loss: 28.8927 - val_loss: 29.1079

Epoch 17/150

89/89 - 7s - 74ms/step - loss: 28.8604 - val_loss: 29.0928

Epoch 18/150

89/89 - 7s - 75ms/step - loss: 28.8466 - val_loss: 29.0848

Epoch 19/150

89/89 - 7s - 76ms/step - loss: 28.8395 - val_loss: 29.0827

Epoch 20/150

89/89 - 7s - 77ms/step - loss: 28.8345 - val_loss: 29.0807

Epoch 21/150

89/89 - 7s - 77ms/step - loss: 28.8323 - val_loss: 29.0800

Epoch 22/150

89/89 - 7s - 83ms/step - loss: 28.8301 - val_loss: 29.0780

Epoch 23/150

89/89 - 7s - 78ms/step - loss: 28.8277 - val_loss: 29.0765

Epoch 24/150

89/89 - 7s - 77ms/step - loss: 28.8239 - val_loss: 29.0726

Epoch 25/150

89/89 - 7s - 77ms/step - loss: 28.8195 - val_loss: 29.0692

Epoch 26/150

89/89 - 7s - 77ms/step - loss: 28.8117 - val_loss: 29.0567

Epoch 27/150

89/89 - 7s - 77ms/step - loss: 28.7993 - val_loss: 29.0309

Epoch 28/150

89/89 - 7s - 78ms/step - loss: 28.4389 - val_loss: 29.0507

Epoch 29/150

89/89 - 7s - 78ms/step - loss: 28.5143 - val_loss: 28.0658

Epoch 30/150

89/89 - 7s - 78ms/step - loss: 25.9986 - val_loss: 23.3140

Epoch 31/150

89/89 - 7s - 79ms/step - loss: 22.1279 - val_loss: 20.5905

Epoch 32/150

89/89 - 7s - 79ms/step - loss: 20.0750 - val_loss: 18.6282

Epoch 33/150

89/89 - 7s - 77ms/step - loss: 18.5706 - val_loss: 17.1705

Epoch 34/150

89/89 - 7s - 77ms/step - loss: 17.3790 - val_loss: 16.7683

Epoch 35/150

89/89 - 7s - 76ms/step - loss: 16.3142 - val_loss: 15.4738

Epoch 36/150

89/89 - 7s - 76ms/step - loss: 15.7447 - val_loss: 15.3336

Epoch 37/150

89/89 - 7s - 78ms/step - loss: 15.3909 - val_loss: 14.3435

Epoch 38/150

89/89 - 7s - 79ms/step - loss: 14.9148 - val_loss: 14.2751

Epoch 39/150

89/89 - 7s - 75ms/step - loss: 14.3909 - val_loss: 14.8587

Epoch 40/150

89/89 - 7s - 76ms/step - loss: 14.0571 - val_loss: 14.9950

Epoch 41/150

89/89 - 7s - 76ms/step - loss: 13.7474 - val_loss: 16.1984

Epoch 42/150

89/89 - 7s - 75ms/step - loss: 13.8463 - val_loss: 13.5698

Epoch 43/150

89/89 - 7s - 77ms/step - loss: 13.4794 - val_loss: 13.9732

Epoch 44/150

89/89 - 7s - 78ms/step - loss: 13.2127 - val_loss: 14.8816

Epoch 45/150

89/89 - 7s - 76ms/step - loss: 13.2212 - val_loss: 13.3127

Epoch 46/150

89/89 - 7s - 76ms/step - loss: 12.9195 - val_loss: 13.6147

Epoch 47/150

89/89 - 7s - 78ms/step - loss: 12.7508 - val_loss: 13.4286

Epoch 48/150

89/89 - 7s - 78ms/step - loss: 12.6101 - val_loss: 13.9458

Epoch 49/150

89/89 - 7s - 76ms/step - loss: 12.4116 - val_loss: 14.2691

Epoch 50/150

89/89 - 7s - 77ms/step - loss: 12.3395 - val_loss: 14.4323

Epoch 51/150

89/89 - 7s - 79ms/step - loss: 12.3166 - val_loss: 14.3853

Epoch 52/150

89/89 - 7s - 79ms/step - loss: 12.1578 - val_loss: 14.6870

Epoch 53/150

89/89 - 7s - 77ms/step - loss: 12.2481 - val_loss: 14.2441

Epoch 54/150

89/89 - 7s - 77ms/step - loss: 12.0769 - val_loss: 13.5874

Epoch 55/150

89/89 - 7s - 77ms/step - loss: 11.9343 - val_loss: 13.4921

Epoch 56/150

89/89 - 7s - 79ms/step - loss: 11.8506 - val_loss: 13.8881

Epoch 57/150

89/89 - 8s - 86ms/step - loss: 11.7874 - val_loss: 13.6149

Epoch 58/150

89/89 - 10s - 108ms/step - loss: 11.6826 - val_loss: 13.5239

Epoch 59/150

89/89 - 8s - 94ms/step - loss: 11.5770 - val_loss: 13.5190

Epoch 60/150

89/89 - 8s - 94ms/step - loss: 11.5462 - val_loss: 13.4273

{'seed': 456, 'epochs_run': 60, 'best_epoch': 45, 'best_val_loss': 13.312740325927734, 'final_train_loss': 11.54624080657959, 'constant_val_loss': 29.081470489501953, 'ratio': 0.45777397435021266, 'converged': True, 'minutes': 7.038733601570129}

Epoch 1/150

89/89 - 9s - 105ms/step - loss: 117.5731 - val_loss: 103.3323

Epoch 2/150

89/89 - 8s - 87ms/step - loss: 96.3027 - val_loss: 88.4822

Epoch 3/150

89/89 - 7s - 79ms/step - loss: 83.1227 - val_loss: 76.8167

Epoch 4/150

89/89 - 7s - 80ms/step - loss: 72.3398 - val_loss: 67.0575

Epoch 5/150

89/89 - 7s - 82ms/step - loss: 63.2274 - val_loss: 58.7957

Epoch 6/150

89/89 - 7s - 77ms/step - loss: 55.5041 - val_loss: 51.8103

Epoch 7/150

89/89 - 7s - 77ms/step - loss: 48.9564 - val_loss: 45.9131

Epoch 8/150

89/89 - 7s - 78ms/step - loss: 43.4334 - val_loss: 40.9619

Epoch 9/150

89/89 - 7s - 82ms/step - loss: 38.8031 - val_loss: 36.8067

Epoch 10/150

89/89 - 7s - 79ms/step - loss: 34.9308 - val_loss: 33.3376

Epoch 11/150

89/89 - 7s - 80ms/step - loss: 31.7160 - val_loss: 30.4532

Epoch 12/150

89/89 - 7s - 83ms/step - loss: 29.4057 - val_loss: 29.3251

Epoch 13/150

89/89 - 7s - 79ms/step - loss: 29.0478 - val_loss: 29.2161

Epoch 14/150

89/89 - 7s - 82ms/step - loss: 28.9555 - val_loss: 29.1514

Epoch 15/150

89/89 - 7s - 82ms/step - loss: 28.9021 - val_loss: 29.1162

Epoch 16/150

89/89 - 7s - 79ms/step - loss: 28.8714 - val_loss: 29.0970

Epoch 17/150

89/89 - 7s - 77ms/step - loss: 28.8540 - val_loss: 29.0870

Epoch 18/150

89/89 - 7s - 73ms/step - loss: 28.8417 - val_loss: 29.0788

Epoch 19/150

89/89 - 7s - 78ms/step - loss: 28.8296 - val_loss: 29.0654

Epoch 20/150

89/89 - 7s - 78ms/step - loss: 28.8368 - val_loss: 29.0845

Epoch 21/150

89/89 - 7s - 80ms/step - loss: 28.8318 - val_loss: 29.0678

Epoch 22/150

89/89 - 7s - 77ms/step - loss: 28.8144 - val_loss: 29.0554

Epoch 23/150

89/89 - 7s - 81ms/step - loss: 28.8059 - val_loss: 29.0480

Epoch 24/150

89/89 - 7s - 78ms/step - loss: 28.7500 - val_loss: 28.6287

Epoch 25/150

89/89 - 7s - 78ms/step - loss: 26.8635 - val_loss: 24.5516

Epoch 26/150

89/89 - 8s - 92ms/step - loss: 22.2048 - val_loss: 21.7194

Epoch 27/150

89/89 - 9s - 96ms/step - loss: 19.9963 - val_loss: 18.3009

Epoch 28/150

89/89 - 7s - 77ms/step - loss: 18.4727 - val_loss: 17.4930

Epoch 29/150

89/89 - 7s - 81ms/step - loss: 18.0678 - val_loss: 19.2955

Epoch 30/150

89/89 - 7s - 81ms/step - loss: 17.3750 - val_loss: 16.7302

Epoch 31/150

89/89 - 7s - 78ms/step - loss: 17.0459 - val_loss: 17.6547

Epoch 32/150

89/89 - 7s - 77ms/step - loss: 16.6006 - val_loss: 17.6552

Epoch 33/150

89/89 - 7s - 77ms/step - loss: 16.2551 - val_loss: 16.4484

Epoch 34/150

89/89 - 7s - 77ms/step - loss: 15.9321 - val_loss: 16.1696

Epoch 35/150

89/89 - 7s - 79ms/step - loss: 15.6654 - val_loss: 16.4463

Epoch 36/150

89/89 - 7s - 78ms/step - loss: 15.5376 - val_loss: 16.1774

Epoch 37/150

89/89 - 7s - 78ms/step - loss: 15.3415 - val_loss: 16.0037

Epoch 38/150

89/89 - 7s - 79ms/step - loss: 15.1925 - val_loss: 15.6228

Epoch 39/150

89/89 - 7s - 79ms/step - loss: 15.0011 - val_loss: 15.9382

Epoch 40/150

89/89 - 7s - 78ms/step - loss: 15.0410 - val_loss: 15.6446

Epoch 41/150

89/89 - 7s - 80ms/step - loss: 14.6138 - val_loss: 16.4276

Epoch 42/150

89/89 - 7s - 79ms/step - loss: 14.8630 - val_loss: 16.0139

Epoch 43/150

89/89 - 7s - 80ms/step - loss: 14.5304 - val_loss: 15.6552

Epoch 44/150

89/89 - 7s - 77ms/step - loss: 14.6179 - val_loss: 15.6891

Epoch 45/150

89/89 - 7s - 78ms/step - loss: 14.3362 - val_loss: 15.4992

Epoch 46/150

89/89 - 7s - 80ms/step - loss: 14.2366 - val_loss: 15.4562

Epoch 47/150

89/89 - 7s - 80ms/step - loss: 14.0098 - val_loss: 15.5199

Epoch 48/150

89/89 - 7s - 81ms/step - loss: 13.8515 - val_loss: 16.7517

Epoch 49/150

89/89 - 7s - 80ms/step - loss: 13.7885 - val_loss: 16.2489

Epoch 50/150

89/89 - 7s - 80ms/step - loss: 13.6433 - val_loss: 16.7795

Epoch 51/150

89/89 - 7s - 81ms/step - loss: 13.5704 - val_loss: 16.6160

Epoch 52/150

89/89 - 7s - 82ms/step - loss: 13.4604 - val_loss: 15.8469

Epoch 53/150

89/89 - 7s - 80ms/step - loss: 13.2584 - val_loss: 15.7890

Epoch 54/150

89/89 - 7s - 78ms/step - loss: 13.1382 - val_loss: 15.5207

Epoch 55/150

89/89 - 7s - 78ms/step - loss: 13.0567 - val_loss: 15.5043

Epoch 56/150

89/89 - 7s - 78ms/step - loss: 12.9860 - val_loss: 15.5591

Epoch 57/150

89/89 - 7s - 78ms/step - loss: 12.8887 - val_loss: 15.4402

Epoch 58/150

89/89 - 7s - 78ms/step - loss: 12.8541 - val_loss: 15.4451

Epoch 59/150

89/89 - 7s - 78ms/step - loss: 12.7770 - val_loss: 15.5377

Epoch 60/150

89/89 - 7s - 79ms/step - loss: 12.6489 - val_loss: 15.5155

Epoch 61/150

89/89 - 7s - 78ms/step - loss: 12.6542 - val_loss: 15.4525

Epoch 62/150

89/89 - 7s - 80ms/step - loss: 12.5919 - val_loss: 15.4398

Epoch 63/150

89/89 - 7s - 81ms/step - loss: 12.4991 - val_loss: 15.3955

Epoch 64/150

89/89 - 7s - 82ms/step - loss: 12.4183 - val_loss: 15.7369

Epoch 65/150

89/89 - 7s - 81ms/step - loss: 12.4055 - val_loss: 15.6375

Epoch 66/150

89/89 - 7s - 81ms/step - loss: 12.3296 - val_loss: 15.4293

Epoch 67/150

89/89 - 7s - 82ms/step - loss: 12.2512 - val_loss: 15.3457

Epoch 68/150

89/89 - 7s - 80ms/step - loss: 12.2002 - val_loss: 15.4567

Epoch 69/150

89/89 - 7s - 82ms/step - loss: 12.2621 - val_loss: 15.1666

Epoch 70/150

89/89 - 7s - 79ms/step - loss: 12.3360 - val_loss: 16.1649

Epoch 71/150

89/89 - 7s - 80ms/step - loss: 12.1885 - val_loss: 15.4196

Epoch 72/150

89/89 - 8s - 85ms/step - loss: 12.1475 - val_loss: 15.7826

Epoch 73/150

89/89 - 9s - 98ms/step - loss: 11.9427 - val_loss: 15.5744

Epoch 74/150

89/89 - 7s - 78ms/step - loss: 11.9839 - val_loss: 16.5544

Epoch 75/150

89/89 - 7s - 78ms/step - loss: 11.8533 - val_loss: 15.8296

Epoch 76/150

89/89 - 7s - 80ms/step - loss: 11.6529 - val_loss: 15.5974

Epoch 77/150

89/89 - 7s - 80ms/step - loss: 11.5761 - val_loss: 15.2825

Epoch 78/150

89/89 - 7s - 79ms/step - loss: 11.4264 - val_loss: 15.4183

Epoch 79/150

89/89 - 7s - 79ms/step - loss: 11.4322 - val_loss: 15.4509

Epoch 80/150

89/89 - 7s - 80ms/step - loss: 11.3771 - val_loss: 15.6498

Epoch 81/150

89/89 - 7s - 79ms/step - loss: 11.3500 - val_loss: 15.5794

Epoch 82/150

89/89 - 7s - 80ms/step - loss: 11.2247 - val_loss: 15.9282

Epoch 83/150

89/89 - 7s - 79ms/step - loss: 11.2880 - val_loss: 15.9699

Epoch 84/150

89/89 - 7s - 81ms/step - loss: 11.2759 - val_loss: 15.4423

{'seed': 789, 'epochs_run': 84, 'best_epoch': 69, 'best_val_loss': 15.166589736938477, 'final_train_loss': 11.27593994140625, 'constant_val_loss': 29.081470489501953, 'ratio': 0.5215207306113845, 'converged': True, 'minutes': 10.001429001490274}

Epoch 1/150

89/89 - 8s - 93ms/step - loss: 118.3073 - val_loss: 104.4590

Epoch 2/150

89/89 - 6s - 71ms/step - loss: 97.3484 - val_loss: 89.5158

Epoch 3/150

89/89 - 7s - 75ms/step - loss: 84.0850 - val_loss: 77.7513

Epoch 4/150

89/89 - 7s - 77ms/step - loss: 73.2423 - val_loss: 67.9617

Epoch 5/150

89/89 - 7s - 81ms/step - loss: 64.1162 - val_loss: 59.6803

Epoch 6/150

89/89 - 7s - 79ms/step - loss: 56.3702 - val_loss: 52.6643

Epoch 7/150

89/89 - 7s - 79ms/step - loss: 49.7964 - val_loss: 46.7360

Epoch 8/150

89/89 - 7s - 80ms/step - loss: 44.2186 - val_loss: 41.7304

Epoch 9/150

89/89 - 7s - 79ms/step - loss: 39.5304 - val_loss: 37.5185

Epoch 10/150

89/89 - 7s - 81ms/step - loss: 35.5984 - val_loss: 33.9906

Epoch 11/150

89/89 - 7s - 81ms/step - loss: 32.3045 - val_loss: 31.0340

Epoch 12/150

89/89 - 7s - 79ms/step - loss: 29.6821 - val_loss: 29.2971

Epoch 13/150

89/89 - 7s - 78ms/step - loss: 29.0085 - val_loss: 29.1879

Epoch 14/150

89/89 - 7s - 79ms/step - loss: 28.9302 - val_loss: 29.1349

Epoch 15/150

89/89 - 7s - 79ms/step - loss: 28.8866 - val_loss: 29.1060

Epoch 16/150

89/89 - 7s - 82ms/step - loss: 28.8619 - val_loss: 29.0917

Epoch 17/150

89/89 - 7s - 82ms/step - loss: 28.8485 - val_loss: 29.0848

Epoch 18/150

89/89 - 7s - 81ms/step - loss: 28.8416 - val_loss: 29.0818

Epoch 19/150

89/89 - 7s - 79ms/step - loss: 28.8379 - val_loss: 29.0817

Epoch 20/150

89/89 - 7s - 80ms/step - loss: 28.8369 - val_loss: 29.0812

Epoch 21/150

89/89 - 7s - 79ms/step - loss: 28.8361 - val_loss: 29.0812

Epoch 22/150

89/89 - 7s - 79ms/step - loss: 28.8357 - val_loss: 29.0823

Epoch 23/150

89/89 - 7s - 81ms/step - loss: 28.8350 - val_loss: 29.0808

Epoch 24/150

89/89 - 8s - 86ms/step - loss: 28.8443 - val_loss: 29.0859

Epoch 25/150

89/89 - 7s - 79ms/step - loss: 28.2072 - val_loss: 25.5627

Epoch 26/150

89/89 - 8s - 91ms/step - loss: 24.8160 - val_loss: 24.2936

Epoch 27/150

89/89 - 8s - 86ms/step - loss: 21.6599 - val_loss: 18.9667

Epoch 28/150

89/89 - 10s - 109ms/step - loss: 18.7460 - val_loss: 18.1571

Epoch 29/150

89/89 - 8s - 86ms/step - loss: 17.7459 - val_loss: 16.2483

Epoch 30/150

89/89 - 7s - 76ms/step - loss: 16.0725 - val_loss: 15.6660

Epoch 31/150

89/89 - 7s - 77ms/step - loss: 15.1619 - val_loss: 15.8940

Epoch 32/150

89/89 - 7s - 77ms/step - loss: 14.7527 - val_loss: 14.7136

Epoch 33/150

89/89 - 7s - 75ms/step - loss: 14.2911 - val_loss: 13.6855

Epoch 34/150

89/89 - 7s - 76ms/step - loss: 13.8863 - val_loss: 13.3545

Epoch 35/150

89/89 - 7s - 77ms/step - loss: 13.6992 - val_loss: 12.2885

Epoch 36/150

89/89 - 7s - 77ms/step - loss: 13.4698 - val_loss: 11.5895

Epoch 37/150

89/89 - 7s - 77ms/step - loss: 13.2226 - val_loss: 11.5804

Epoch 38/150

89/89 - 7s - 78ms/step - loss: 13.0407 - val_loss: 11.2713

Epoch 39/150

89/89 - 7s - 77ms/step - loss: 12.8945 - val_loss: 11.7727

Epoch 40/150

89/89 - 7s - 79ms/step - loss: 12.6718 - val_loss: 11.9616

Epoch 41/150

89/89 - 7s - 76ms/step - loss: 12.6118 - val_loss: 12.1518

Epoch 42/150

89/89 - 7s - 78ms/step - loss: 12.5705 - val_loss: 12.5585

Epoch 43/150

89/89 - 7s - 79ms/step - loss: 12.3780 - val_loss: 13.3344

Epoch 44/150

89/89 - 7s - 79ms/step - loss: 12.2822 - val_loss: 13.1637

Epoch 45/150

89/89 - 7s - 78ms/step - loss: 12.2416 - val_loss: 12.6680

Epoch 46/150

89/89 - 7s - 78ms/step - loss: 12.1919 - val_loss: 12.7276

Epoch 47/150

89/89 - 7s - 78ms/step - loss: 11.9660 - val_loss: 12.3183

Epoch 48/150

89/89 - 7s - 76ms/step - loss: 11.9679 - val_loss: 12.4160

Epoch 49/150

89/89 - 7s - 77ms/step - loss: 11.8484 - val_loss: 12.6799

Epoch 50/150

89/89 - 7s - 78ms/step - loss: 11.7155 - val_loss: 12.5242

Epoch 51/150

89/89 - 7s - 79ms/step - loss: 11.6659 - val_loss: 13.1270

Epoch 52/150

89/89 - 7s - 79ms/step - loss: 11.5755 - val_loss: 12.7596

Epoch 53/150

89/89 - 7s - 84ms/step - loss: 11.5395 - val_loss: 12.8915

{'seed': 1000, 'epochs_run': 53, 'best_epoch': 38, 'best_val_loss': 11.271327018737793, 'final_train_loss': 11.5394926071167, 'constant_val_loss': 29.081470489501953, 'ratio': 0.3875776165722638, 'converged': True, 'minutes': 6.285669811566671}

,seed,epochs_run,best_epoch,best_val_loss,final_train_loss,constant_val_loss,ratio,converged,minutes
0,42,86,71,11.079,10.107,29.081,0.381,True,10.852
1,123,90,75,10.604,9.965,29.081,0.365,True,10.861
2,456,60,45,13.313,11.546,29.081,0.458,True,7.039
3,789,84,69,15.167,11.276,29.081,0.522,True,10.001
4,1000,53,38,11.271,11.539,29.081,0.388,True,6.286

## Part C: evaluation on the held-out Regime 0 test windows (run only after Part B is saved)

In [6]:
assert (OUT / "convergence_check.csv").exists(), "Run Part B first."

def cq(scores, a):
    n = len(scores)
    return float(np.quantile(scores, min(1.0, np.ceil((n + 1) * (1 - a)) / n), method="higher"))

def stage_of(r):
    return np.where(r > 80, "Early", np.where(r > 40, "Mid", "Late"))

def winkler(y, lo, hi, a):
    return (hi - lo) + (2 / a) * (lo - y) * (y < lo) + (2 / a) * (y - hi) * (y > hi)

A = P["calibration"]["alpha"]
rows, engine_rows, stage_rows, global_rows = [], [], [], []
for seed in P["model_seeds"]:
    model = tf.keras.models.load_model(OUT / "models" / f"DS_A_rerun_seed{seed}.keras")
    pc = model.predict(X_cal, batch_size=512, verbose=0)
    pt = model.predict(X_test, batch_size=512, verbose=0)

    ql, qu = cq(pc[:, 0] - y_cal, A / 2), cq(y_cal - pc[:, 2], A / 2)
    err = np.maximum(pc[:, 0] - y_cal, y_cal - pc[:, 2])
    eng_q80 = np.array([np.quantile(err[id_cal == e], 0.80) for e in np.unique(id_cal)])
    M = len(eng_q80)
    qb = float(np.quantile(eng_q80, min(1.0, np.ceil((M + 1) * (1 - A)) / M), method="higher"))

    df = pd.DataFrame({"seed": seed, "engine_id": id_test, "cycle": cyc_test, "true_RUL": y_test,
                       "q10": pt[:, 0], "q50": pt[:, 1], "q90": pt[:, 2], "stage": stage_of(y_test)})
    df["asym_lower"] = np.maximum(0, df.q10 - ql); df["asym_upper"] = np.maximum(0, df.q90 + qu)
    df["bal_lower"] = np.maximum(0, df.q10 - qb); df["bal_upper"] = np.maximum(0, df.q90 + qb)
    for m in ["asym", "bal"]:
        df[f"{m}_covered"] = (df.true_RUL >= df[f"{m}_lower"]) & (df.true_RUL <= df[f"{m}_upper"])
        df[f"{m}_winkler"] = winkler(df.true_RUL, df[f"{m}_lower"], df[f"{m}_upper"], A)
    df["error_q50_minus_true"] = df.q50 - df.true_RUL
    rows.append(df)
    pd.DataFrame({"seed": seed, "engine_id": id_cal, "cycle": cyc_cal, "true_RUL": y_cal,
                  "q10": pc[:, 0], "q50": pc[:, 1], "q90": pc[:, 2]}
                 ).to_csv(OUT / f"calibration_predictions_seed{seed}.csv", index=False)

    rmse = float(np.sqrt(np.mean(df.error_q50_minus_true ** 2)))
    for m, name in [("asym", "Asymmetric CQR"), ("bal", "Balanced Engine CQR")]:
        global_rows.append({"seed": seed, "method": name, "RMSE": rmse, "MAE": float(df.error_q50_minus_true.abs().mean()),
                            "PICP": 100 * df[f"{m}_covered"].mean(), "MPIW": float((df[f"{m}_upper"] - df[f"{m}_lower"]).mean()),
                            "Winkler": float(df[f"{m}_winkler"].mean()),
                            "Q_lower": ql if m == "asym" else qb, "Q_upper": qu if m == "asym" else qb})
    for e, g in df.groupby("engine_id"):
        engine_rows.append({"seed": seed, "engine_id": e, "n_windows": len(g),
                            "RMSE": float(np.sqrt(np.mean(g.error_q50_minus_true ** 2))), "MAE": float(g.error_q50_minus_true.abs().mean()),
                            "bias": float(g.error_q50_minus_true.mean()),
                            "Asym_Coverage": 100 * g.asym_covered.mean(), "Bal_Coverage": 100 * g.bal_covered.mean(),
                            "Asym_Width": float((g.asym_upper - g.asym_lower).mean()), "Bal_Width": float((g.bal_upper - g.bal_lower).mean())})
    for s, g in df.groupby("stage"):
        stage_rows.append({"seed": seed, "stage": s, "N": len(g), "RMSE": float(np.sqrt(np.mean(g.error_q50_minus_true ** 2))),
                           "MAE": float(g.error_q50_minus_true.abs().mean()), "signed_bias": float(g.error_q50_minus_true.mean()),
                           "Asym_Coverage": 100 * g.asym_covered.mean(), "Bal_Coverage": 100 * g.bal_covered.mean()})

pred = pd.concat(rows, ignore_index=True)
pred.to_csv(OUT / "test_predictions_rowlevel.csv", index=False)
glob = pd.DataFrame(global_rows).merge(train_log[["seed", "converged"]], on="seed")
per_engine = pd.DataFrame(engine_rows)
stages = pd.DataFrame(stage_rows)
glob.to_csv(OUT / "global_by_seed.csv", index=False)
per_engine.to_csv(OUT / "per_engine_by_seed.csv", index=False)
stages.to_csv(OUT / "life_stage_by_seed.csv", index=False)
display(glob.round(3))

,seed,method,RMSE,MAE,PICP,MPIW,Winkler,Q_lower,Q_upper,converged
0,42,Asymmetric CQR,24.097,16.216,73.568,45.237,74.496,1.291,0.074,True
1,42,Balanced Engine CQR,24.097,16.216,91.043,68.851,80.311,12.866,12.866,True
2,123,Asymmetric CQR,22.905,14.752,72.051,37.448,72.948,1.116,0.199,True
3,123,Balanced Engine CQR,22.905,14.752,88.546,60.449,75.358,12.606,12.606,True
4,456,Asymmetric CQR,25.316,16.209,76.016,50.325,80.190,1.540,1.747,True
5,456,Balanced Engine CQR,25.316,16.209,90.553,73.110,85.844,13.660,13.660,True
6,789,Asymmetric CQR,27.544,18.208,78.463,56.803,91.649,4.997,7.608,True
7,789,Balanced Engine CQR,27.544,18.208,90.798,83.129,96.530,20.748,20.748,True
8,1000,Asymmetric CQR,25.158,15.501,73.470,43.875,79.978,-1.547,2.338,True
9,1000,Balanced Engine CQR,25.158,15.501,88.350,65.389,81.632,11.668,11.668,True

In [7]:
# Engine-level summaries (Table 5 style), RMSE-coverage correlation, problem engines
from scipy.stats import pearsonr, spearmanr

summ = []
for (seed, m), col in [((s, m), c) for s in P["model_seeds"] for m, c in [("Asymmetric CQR", "Asym_Coverage"), ("Balanced Engine CQR", "Bal_Coverage")]]:
    v = per_engine.loc[per_engine.seed == seed, col].to_numpy()
    summ.append({"seed": seed, "method": m, "mean": v.mean(), "median": np.median(v), "p10": np.percentile(v, 10),
                 "p25": np.percentile(v, 25), "worst": v.min(), "below80": int((v < 80).sum()), "below70": int((v < 70).sum())})
summ = pd.DataFrame(summ)
summ.to_csv(OUT / "engine_level_summary_by_seed.csv", index=False)

corr = []
for seed, g in per_engine.groupby("seed"):
    r, pr = pearsonr(g.RMSE, g.Bal_Coverage); rho, ps = spearmanr(g.RMSE, g.Bal_Coverage)
    corr.append({"seed": seed, "pearson_r": r, "pearson_p": pr, "spearman_rho": rho, "spearman_p": ps,
                 "problem_engines_bal_below80": " ".join(map(str, sorted(g.loc[g.Bal_Coverage < 80, "engine_id"])))})
corr = pd.DataFrame(corr)
corr.to_csv(OUT / "rmse_coverage_correlation_by_seed.csv", index=False)
display(summ.round(2)); display(corr.round(3))

,seed,method,mean,median,p10,p25,worst,below80,below70
0,42,Asymmetric CQR,69.00,73.57,37.60,53.68,18.52,23,17
1,42,Balanced Engine CQR,88.07,93.46,65.71,84.58,40.74,8,6
2,123,Asymmetric CQR,69.43,66.29,40.76,47.89,24.00,20,20
3,123,Balanced Engine CQR,86.09,94.82,59.69,78.42,50.00,11,8
4,456,Asymmetric CQR,72.51,77.60,42.49,58.56,28.00,19,18
5,456,Balanced Engine CQR,88.03,92.72,70.26,79.38,48.00,11,3
6,789,Asymmetric CQR,74.66,81.17,46.38,66.38,22.22,18,12
7,789,Balanced Engine CQR,88.77,95.39,68.97,84.09,40.00,6,4
8,1000,Asymmetric CQR,69.44,73.76,36.63,55.22,28.00,23,18
9,1000,Balanced Engine CQR,86.12,89.59,64.77,81.43,44.00,9,5

,seed,pearson_r,pearson_p,spearman_rho,spearman_p,problem_engines_bal_below80
0,42,-0.947,0.0,-0.962,0.0,17 105 115 156 184 194 240 245
1,123,-0.954,0.0,-0.952,0.0,17 26 105 115 120 156 181 184 194 240 245
2,456,-0.957,0.0,-0.846,0.0,17 70 85 105 115 120 156 184 194 240 245
3,789,-0.924,0.0,-0.856,0.0,17 105 115 156 184 240
4,1000,-0.920,0.0,-0.866,0.0,17 85 105 115 156 184 194 240 245

In [8]:
# Engine-cluster bootstrap (10,000 replicates) for global PICP/MPIW and the paired Balanced - Asymmetric difference
B = P["bootstrap"]
boot_rows = []
for seed in P["model_seeds"]:
    g = pred[pred.seed == seed]
    agg = g.groupby("engine_id").agg(n=("true_RUL", "size"), ca=("asym_covered", "sum"), cb=("bal_covered", "sum"),
                                     wa=("asym_upper", "sum"), wb=("bal_upper", "sum"),
                                     la=("asym_lower", "sum"), lb=("bal_lower", "sum"))
    n, ca, cb = agg.n.to_numpy(), agg.ca.to_numpy(), agg.cb.to_numpy()
    wa, wb = (agg.wa - agg.la).to_numpy(), (agg.wb - agg.lb).to_numpy()
    rng = np.random.default_rng(B["rng_seed"])
    idx = rng.integers(0, len(n), size=(B["replicates"], len(n)))
    N = n[idx].sum(1)
    stats = {"asym_picp": 100 * ca[idx].sum(1) / N, "bal_picp": 100 * cb[idx].sum(1) / N,
             "asym_mpiw": wa[idx].sum(1) / N, "bal_mpiw": wb[idx].sum(1) / N}
    stats["bal_minus_asym_picp"] = stats["bal_picp"] - stats["asym_picp"]
    point = {"asym_picp": 100 * ca.sum() / n.sum(), "bal_picp": 100 * cb.sum() / n.sum(),
             "asym_mpiw": wa.sum() / n.sum(), "bal_mpiw": wb.sum() / n.sum()}
    point["bal_minus_asym_picp"] = point["bal_picp"] - point["asym_picp"]
    for k, v in stats.items():
        lo, hi = np.percentile(v, B["ci"])
        boot_rows.append({"seed": seed, "stat": k, "point": point[k], "ci_low": lo, "ci_high": hi})
boot = pd.DataFrame(boot_rows)
boot.to_csv(OUT / "bootstrap_by_seed.csv", index=False)
display(boot.round(2))

    seed                 stat  point  ci_low  ci_high
0     42            asym_picp  73.57   67.03    79.56
1     42             bal_picp  91.04   86.88    94.39
2     42            asym_mpiw  45.24   43.55    47.04
3     42             bal_mpiw  68.85   67.19    70.64
4     42  bal_minus_asym_picp  17.47   13.86    21.33
5    123            asym_picp  72.05   64.76    79.00
6    123             bal_picp  88.55   84.22    92.42
7    123            asym_mpiw  37.45   36.00    39.03
8    123             bal_mpiw  60.45   59.06    61.97
9    123  bal_minus_asym_picp  16.50   12.69    20.47
10   456            asym_picp  76.02   69.55    81.84
11   456             bal_picp  90.55   86.95    93.58
12   456            asym_mpiw  50.33   50.04    50.66
13   456             bal_mpiw  73.11   72.85    73.41
14   456  bal_minus_asym_picp  14.54   11.15    18.26
15   789            asym_picp  78.46   72.62    83.49
16   789             bal_picp  90.80   87.04    94.04
17   789            asym_mpiw  56.80   56.44    57.21
18   789             bal_mpiw  83.13   82.72    83.59
19   789  bal_minus_asym_picp  12.33    9.75    15.21
20  1000            asym_picp  73.47   66.98    79.38
21  1000             bal_picp  88.35   84.20    92.05
22  1000            asym_mpiw  43.88   43.61    44.12
23  1000             bal_mpiw  65.39   64.97    65.78
24  1000  bal_minus_asym_picp  14.88   11.82    18.33

In [9]:
# Five-seed summary: all seeds (primary) and converged seeds only (secondary)
def agg(df, label):
    out = df.groupby("method")[["PICP", "MPIW", "Winkler", "RMSE", "MAE"]].agg(["mean", "std"])
    out.columns = [f"{a}_{b}" for a, b in out.columns]
    out.insert(0, "n_seeds", df.groupby("method").size())
    out.insert(0, "seeds", label)
    return out.reset_index()

five = pd.concat([agg(glob, "all"), agg(glob[glob.converged], "converged only")], ignore_index=True)
five.to_csv(OUT / "five_seed_summary.csv", index=False)
display(five.round(3))

stage_summary = stages.groupby("stage")[["RMSE", "signed_bias", "Bal_Coverage", "Asym_Coverage"]].agg(["mean", "std"]).round(2)
stage_summary.to_csv(OUT / "life_stage_five_seed_summary.csv")
display(stage_summary)

frozen = {"RMSE": 24.869, "Asym PICP": 73.13, "Bal PICP": 90.21}
s42 = glob[glob.seed == 42].set_index("method")
if len(s42):
    print("Seed 42 vs archived frozen summary (for reference only, not a gate):")
    print(f"  RMSE {s42.RMSE.iloc[0]:.3f} vs {frozen['RMSE']} | Asym {s42.loc['Asymmetric CQR','PICP']:.2f} vs {frozen['Asym PICP']}"
          f" | Balanced {s42.loc['Balanced Engine CQR','PICP']:.2f} vs {frozen['Bal PICP']}")

manifest = {p.name: hashlib.sha256(p.read_bytes()).hexdigest() for p in sorted(OUT.rglob("*")) if p.is_file()}
(OUT / "manifest_sha256.json").write_text(json.dumps(manifest, indent=2))
print(f"Done. {len(manifest)} files hashed in", OUT)

,method,seeds,n_seeds,PICP_mean,PICP_std,MPIW_mean,MPIW_std,Winkler_mean,Winkler_std,RMSE_mean,RMSE_std,MAE_mean,MAE_std
0,Asymmetric CQR,all,5,74.714,2.535,46.738,7.262,79.852,7.343,25.004,1.718,16.177,1.286
1,Balanced Engine CQR,all,5,89.858,1.300,70.186,8.598,83.935,7.973,25.004,1.718,16.177,1.286
2,Asymmetric CQR,converged only,5,74.714,2.535,46.738,7.262,79.852,7.343,25.004,1.718,16.177,1.286
3,Balanced Engine CQR,converged only,5,89.858,1.300,70.186,8.598,83.935,7.973,25.004,1.718,16.177,1.286

        RMSE       signed_bias       Bal_Coverage       Asym_Coverage
        mean   std        mean   std         mean   std          mean   std
stage
Early  18.33  1.31       -3.05  2.54        94.43  1.33         83.52  2.22
Late   25.23  4.75       11.05  4.85        89.43  1.87         70.37  5.88
Mid    39.11  3.12       17.64  2.73        75.52  6.36         50.72  6.03

Seed 42 vs archived frozen summary (for reference only, not a gate):
  RMSE 24.097 vs 24.869 | Asym 73.57 vs 73.13 | Balanced 91.04 vs 90.21
Done. 29 files hashed in <FD004_ROOT>/FD004_DS_A_Rerun_Results